version: '3.8'

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
  keycloakdb-data:
    driver: local

services:
  keycloakdb:
    image: postgres:11
    volumes:
      - keycloakdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5433"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: geekocon
      POSTGRES_DB: geekocon
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "8082:81"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
  keycloak:
    image: jboss/keycloak:latest
    volumes:
      - ./imports/startup-scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
      - ./imports/keycloak/realm/realm-export.json:/opt/jboss/keycloak/imports/realm/realm-export.json
      - ./imports/keycloak/standalone/deployments/://opt/jboss/keycloak/standalone/deployments/
      - ./imports/keycloak/themes/ck-theme/login://opt/jboss/keycloak/themes/ck-theme/login
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloakdb # <<< This is the address, change it to your external db ip/domain
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - keycloakdb
