version: '3.8'

volumes:
  postgres-data:
    driver: local
  keycloakdb-data:
    driver: local

services:
  keycloakdb: # Service name 
    image: postgres:11
    volumes:
      - keycloakdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: geekocon
      POSTGRES_USER: geekocon
      POSTGRES_DB: geekocon
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:latest
    volumes:
      - ./imports/keycloak:/opt/jboss/keycloak/imports
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloakdb # <<< This is the address, change it to your external db ip/domain
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - keycloakdb
